version: "3.10"

services:
  frontend:
    build: Streamlit_Frontend
    ports:
      - 8501:8501
    networks:
      - jcnet
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend:/app/backend


  backend:
    build: FastAPI_Backend
    ports:
      - 8000:8000
    networks:
      - jcnet

    volumes:
      - ./FastAPI_Backend:/app/frontend
networks:
  jcnet